### ISSUE TITLE
ServerTap Broken With Latest Paper Version (When Using TikFinity Minecraft Plugin)

### ISSUE THREAD

**Issue by WG-Mojo** [servertap-io/servertap#249]
Servertap works intermittently with the latest version of PaperMC (169) and TikFinity. It works perfectly fine with version 160 of paper.

**Comment by WG-Mojo** [comment]
![image](https://github.com/phybros/servertap/assets/24610819/a3e109fc-ac19-4324-9587-a90f923c9400)

**Comment by heazog** [comment]
I have the exact same issue on spigot-1.20.1-R0.1.
But not only fill commands, more like on every command except help.

**Comment by shawnlihst** [comment]
I am also having the same issue on purpur-1.20.1 2060. I have since rolled back to 2004. I hope this issue can be resolved before purpur-1.20.2 is released.

**Comment by shawnlihst** [comment]
> I have the exact same issue on spigot-1.20.1-R0.1. But not only fill commands, more like on every command except help.

I am also having the same issue on purpur-1.20.1 2060. I have since rolled back to 2004. I hope this issue can be resolved before purpur-1.20.2 is released.

**Comment by shawnlihst** [comment]
> > > I have the exact same issue on spigot-1.20.1-R0.1. But not only fill commands, more like on every command except help.
> > 
> > 
> > I am also having the same issue on purpur-1.20.1 2060. I have since rolled back to 2004. I hope this issue can be resolved before purpur-1.20.2 is released.
> 
> https://github.com/TimeCodings/servertap/releases/tag/v0.5.4

Thank you very much, your branch is available.

**Comment by shawnlihst** [comment]
> > > I have the exact same issue on spigot-1.20.1-R0.1. But not only fill commands, more like on every command except help.
> > 
> > 
> > I am also having the same issue on purpur-1.20.1 2060. I have since rolled back to 2004. I hope this issue can be resolved before purpur-1.20.2 is released.
> 
> https://github.com/TimeCodings/servertap/releases/tag/v0.5.4

Thank you very much, your branch is available.

**Comment by heazog** [comment]
Thank you! it also works now on spigot-1.20.1-R0.1. :)

**Comment by phybros** [comment]
Fixed in the new release 0.6.1!
