### ISSUE TITLE
unable to run plugin on server

### ISSUE THREAD

**Issue by Boundinjax** [servertap-io/servertap#267]
Hi guys comming to see if anyone knows how to resolved this
![image](https://github.com/servertap-io/servertap/assets/162921937/f745bfbd-5b1a-4514-ae34-56d564cb3171)

Versión del servidor v1.20.60
Version de java: java 17

**Comment by Velyn-N** [comment]
As it seems you run a Nukkit server which, according to Google, is a Software for Bedrock Servers.

ServerTap is a Plugin for Spigot (or its forks, inofficially) which is a Server Software for Minecraft Java Edition. Therefore your Server will not be able to run ServerTap.
